//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingAppsAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationsText
    {
        public int Id { get; set; }
        public int AccreditationId { get; set; }
        public string Language { get; set; }
        public string Label { get; set; }
    
        public virtual Accreditation Accreditation { get; set; }
        public virtual Language Language1 { get; set; }
    }
}
