//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingAppsAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public string ISO { get; set; }
        public string Label { get; set; }
        public int Priority { get; set; }
        public bool Active { get; set; }
        public int Id { get; set; }
    }
}
